### ISSUE TITLE
Keyring `system` does not exist with backend_file

### ISSUE THREAD

**Issue by ras44** [r-lib/keyring#68]
I receive the error `Keyring 'system' does not exist` when setting a value:

reprex:

```
library(keyring)

kr_name <- "my_credentials"
kr_service <- "my_service"
kr_username <- "my_username"

kb <- keyring::backend_file$new()
kb$keyring_create(kr_name)
kb$set_with_value(kr_service, kr_username)
kb$keyring_lock(kr_name)
```

**Comment by cderv** [comment]
You get the message because it is looking for the default keyring that does not exist

> kb$set_with_value(kr_service, kr_username)

There is a missing `keyring` argument here because you do not use the default one, but your `kr_name` keyring. Also `set_with_value` is for non interactive use and expect a `password` argument. Use `set` for interactive registration. 
This line should be `kb$set_with_value(kr_service, kr_username, password, keyring = kr_name)`

To create the default system keyring named `system`, use `kb$keyring_create()`

Use `kb$keyring_list()` to see the already existing keyring.

**Comment by ras44** [comment]
Thank you, that fixed it.

Would it be helpful to include a vignette or backend_file example? I would be happy to provide a PR with something along the lines of the above.  Currently the examples in the documentation for `key_set` and `key_set_with_value` only use the default keyring.

**Comment by gaborcsardi** [comment]
@ras44 yes, that would make sense.

**Comment by cderv** [comment]
@gaborcsardi FWIW this should have been closed by #69 I think.

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by nielsenmarkus11** [comment]
@gaborcsardi, because this doesn't have a "default" backend does that mean we can't have the OS automatically unlock it?

**Comment by gaborcsardi** [comment]
The OS can only unlock keyrings that it knows about, so yeah, I am afraid that it cannot automatically unlock the file backend.
